# Generated by Django 2.1.4 on 2018-12-12 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181212_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
